version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: employees
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password123?
      MYSQL_USER: bojan
    volumes:
      - db:/var/lib/mysql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  db:
    driver: local
